slanguage: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

jobs:
  include:
    - stage: build
      script: ./gradlew build

    - stage: test
      script: ./gradlew test
#    - stage: lint
#      script:

#deploy:
#  provider: releases
#  api_key:
#  file: "./app/build/outputs/apk/debug/app-release-signed.apk"
#  skip_cleanup: true
#  on:
#    tags: true


